import 'package:get/get.dart';

class PetListingPageData {
  static const rootPathDog = "images/dog";
  static const rootPathCat = "images/cat";
  Map<String, List<Map<String, dynamic>>> petDataList = {
    "dogData": [
      {
        "imgSrc": "$rootPathDog/1.jpeg",
        "name": "Max",
        "id": "dogData_1",
        "age": "1",
        "price": "100",
        "isAdopted": false.obs,
      },
      {
        "imgSrc": "$rootPathDog/2.jpeg",
        "name": "Bailey",
        "id": "dogData_2",
        "age": "2",
        "price": "200",
        "isAdopted": false.obs,
      },
      {
        "imgSrc": "$rootPathDog/3.jpeg",
        "name": "Stella",
        "id": "dogData_3",
        "age": "3",
        "price": "300",
        "isAdopted": false.obs,
      },
      {
        "imgSrc": "$rootPathDog/4.jpeg",
        "name": "Duke",
        "id": "dogData_4",
        "age": "4",
        "price": "400",
        "isAdopted": false.obs,
      },
      {
        "imgSrc": "$rootPathDog/5.jpeg",
        "name": "Sadie",
        "id": "dogData_5",
        "age": "5",
        "price": "500",
        "isAdopted": false.obs,
      },
      {
        "imgSrc": "$rootPathDog/6.jpeg",
        "name": "Tucker",
        "id": "dogData_6",
        "age": "6",
        "price": "600",
        "isAdopted": false.obs,
      },
      {
        "imgSrc": "$rootPathDog/7.jpeg",
        "name": "Olive",
        "id": "dogData_7",
        "age": "7",
        "price": "700",
        "isAdopted": false.obs,
      },
      {
        "imgSrc": "$rootPathDog/8.jpeg",
        "name": "Milo",
        "id": "dogData_8",
        "age": "8",
        "price": "800",
        "isAdopted": false.obs,
      },
      {
        "imgSrc": "$rootPathDog/9.jpeg",
        "name": "Ruby",
        "id": "dogData_9",
        "age": "9",
        "price": "900",
        "isAdopted": false.obs,
      },
      {
        "imgSrc": "$rootPathDog/10.jpeg",
        "name": "Baxter",
        "id": "dogData_10",
        "age": "8",
        "price": "800",
        "isAdopted": false.obs,
      },
      {
        "imgSrc": "$rootPathDog/11.jpeg",
        "name": "Cooper",
        "id": "dogData_11",
        "age": "7",
        "price": "700",
        "isAdopted": false.obs,
      },
      {
        "imgSrc": "$rootPathDog/12.jpeg",
        "name": "Luna",
        "id": "dogData_12",
        "age": "7",
        "price": "700",
        "isAdopted": false.obs,
      },
      {
        "imgSrc": "$rootPathDog/13.jpeg",
        "name": "Rocky",
        "id": "dogData_13",
        "age": "6",
        "price": "600",
        "isAdopted": false.obs,
      },
      {
        "imgSrc": "$rootPathDog/14.jpeg",
        "name": "Penny",
        "id": "dogData_14",
        "age": "8",
        "price": "800",
        "isAdopted": false.obs,
      },
      {
        "imgSrc": "$rootPathDog/15.jpeg",
        "name": "Bentley",
        "id": "dogData_15",
        "age": "7",
        "price": "700",
        "isAdopted": false.obs,
      },
      {
        "imgSrc": "$rootPathDog/16.jpeg",
        "name": "Hazel",
        "id": "dogData_16",
        "age": "6",
        "price": "600",
        "isAdopted": false.obs,
      },
      {
        "imgSrc": "$rootPathDog/17.jpeg",
        "name": "Charlie",
        "id": "dogData_17",
        "age": "8",
        "price": "800",
        "isAdopted": false.obs,
      },
      {
        "imgSrc": "$rootPathDog/18.jpeg",
        "name": "Rosie",
        "id": "dogData_18",
        "age": "7",
        "price": "700",
        "isAdopted": false.obs,
      },
      {
        "imgSrc": "$rootPathDog/19.jpeg",
        "name": "Jackson",
        "id": "dogData_19",
        "age": "5",
        "price": "500",
        "isAdopted": false.obs,
      },
      {
        "imgSrc": "$rootPathDog/20.jpeg",
        "name": "Willow",
        "id": "dogData_20",
        "age": "9",
        "price": "900",
        "isAdopted": false.obs,
      },
    ],
    "catData": [
      {
        "imgSrc": "$rootPathCat/1.jpeg",
        "name": "Ash",
        "id": "catData_1",
        "age": "9",
        "price": "900",
        "isAdopted": false.obs,
      },
      {
        "imgSrc": "$rootPathCat/2.jpeg",
        "name": "Bella",
        "id": "catData_2",
        "age": "9",
        "price": "900",
        "isAdopted": false.obs,
      },
      {
        "imgSrc": "$rootPathCat/3.jpeg",
        "name": "Coco",
        "id": "catData_3",
        "age": "9",
        "price": "900",
        "isAdopted": false.obs,
      },
      {
        "imgSrc": "$rootPathCat/4.jpeg",
        "name": "Dexter",
        "id": "catData_4",
        "age": "9",
        "price": "900",
        "isAdopted": false.obs,
      },
      {
        "imgSrc": "$rootPathCat/5.jpeg",
        "name": "Ember",
        "id": "catData_5",
        "age": "9",
        "price": "900",
        "isAdopted": false.obs,
      },
      {
        "imgSrc": "$rootPathCat/6.jpeg",
        "name": "Felix",
        "id": "catData_6",
        "age": "9",
        "price": "900",
        "isAdopted": false.obs,
      },
      {
        "imgSrc": "$rootPathCat/7.jpeg",
        "name": "Gizmo",
        "id": "catData_7",
        "age": "9",
        "price": "900",
        "isAdopted": false.obs,
      },
      {
        "imgSrc": "$rootPathCat/8.jpeg",
        "name": "Hazelio",
        "id": "catData_8",
        "age": "9",
        "price": "900",
        "isAdopted": false.obs,
      },
    ],
  };
}
